/**
 * fastdfs protocol constants
 */
export enum ProtocolConstants {
    LENGTH_INDEX = 0,
    CMD_INDEX = 8,
    STATUS_INDEX = 9,
    LENGTH_BYTES = 8,
    GROUP_NAME_MAX_BYTES = 16,
    HEADER_BYTES = 10,
    IP_ADDR_BYTES = 15,
    PORT_BYTES = 8,
    EXT_NAME_BYTES = 6,
    STORAGE_ID_MAX_SIZE = 16,
    DOMAIN_NAME_MAX_BYTES = 128,
    VERSION_SIZE = 6,
    TRACKER_QUERY_STORAGE_STORE_BODY_LEN = 40,
    TRACKER_QUERY_STORAGE_FETCH_BODY_LEN = IP_ADDR_BYTES + GROUP_NAME_MAX_BYTES + PORT_BYTES
}