/**
 * stat of storage server
 */
export interface StorageServerStat {
    status:number,
    id:string,
    ipAddr:string,
    srcIpAddr:string,
    domainName:string,
    version:string,
    joinTime:Date,
    upTime:Date,
    totalMB: bigint,
    freeMB: bigint,
    uploadPriority:number,
    storePathCount:number,
    subdirCountPerPath:number,
    storagePort:number,
    storageHttpPort:number,
    currentWritePath:number,
    connectionAllocCount:number,
    connectionCurrentCount:number,
    connectionMaxCount: number,
    totalUploadCount: bigint,
    successUploadCount: bigint,
    totalAppendCount: bigint,
    totalModifyCount: bigint,
    successModifyCount: bigint,
    totalTruncateCount: bigint,
    successSetMetaCount: bigint,
    totalDeleteCount: bigint,
    successDeleteCount: bigint,
    totalDownalodCount: bigint,
    successDownloadCount: bigint,
    totalGetMetaCount: bigint,
    successGetMetaCount: bigint,
    totalCreateLinkCount: bigint,
    successCreateLinkCount: bigint,
    totalDeleteLinkCount: bigint,
    successDeleteLinkCount: bigint,
    totalUploadBytes: bigint,
    successUploadBytes: bigint,
    totalAppendBytes: bigint,
    successAppendBytes: bigint,
    totalModifyBytes: bigint,
    sucessModifyBytes: bigint,
    totalDownloadBytes: bigint,
    successDownloadBytes: bigint,
    totalSyncInBytes: bigint,
    successSyncInBytes: bigint,
    totalSyncOutBytes: bigint,
    successSyncOutBytes: bigint,
    totalFileOpenCount: bigint,
    successFileOpenCount: bigint,
    totalFileReadCount: bigint,
    successFileReadCount: bigint,
    totalFileWriteCount: bigint,
    successFileWriteCount: bigint,
    lastSourceUpdate: Date,
    lastSyncUpdate: Date,
    lastSyncedTimestamp: Date,
    lastHeartBeatTime: Date,
    ifTrunkServer: boolean
}